apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: tracing-server
  name: tracing-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: tracing-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: tracing-server
    spec:
      containers:
        - image: openzipkin/zipkin
          name: tracing-server
          ports:
            - containerPort: 9411
              protocol: TCP
      restartPolicy: Always
