apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
    kompose.image-pull-secret: regcred
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: vets-service
  name: vets-service
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: vets-service
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -o petclinic_chart/templates
        kompose.image-pull-secret: regcred
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: vets-service
    spec:
      containers:
        - image: '{{ .Values.IMAGE_TAG_VETS_SERVICE }}'
          name: vets-service
          ports:
            - containerPort: 8083
              protocol: TCP
      imagePullSecrets:
        - name: regcred
      restartPolicy: Always
